// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Varons.Custom.SQLProvider")>]
[<assembly: AssemblyProductAttribute("Varons.Custom.SQLProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type providers for SQL database access.")>]
[<assembly: AssemblyVersionAttribute("1.2.8")>]
[<assembly: AssemblyFileVersionAttribute("1.2.8")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Varons.Custom.SQLProvider"
    let [<Literal>] AssemblyProduct = "Varons.Custom.SQLProvider"
    let [<Literal>] AssemblyDescription = "Type providers for SQL database access."
    let [<Literal>] AssemblyVersion = "1.2.8"
    let [<Literal>] AssemblyFileVersion = "1.2.8"
